Repository mattermost/mmctl, pull requests merged in 2019-11, with the labels that each got.

#36 Remove unnecessary gomock operators
  commands/permissions_test.go
  commands/user_test.go
Labels: 3: Reviews Complete

#35 Adds version command
  Makefile
  commands/version.go
Labels: 3: Reviews Complete, QA Review Done

#37 Add tests for the search channel command
  commands/channel_test.go
Labels: 3: Reviews Complete

#42 [MM-20032] Unit testing added for UserCreateCmd
  commands/user_test.go
Labels: 3: Reviews Complete

#39 [GH-13049] Add unit tests to "UserInviteCmd" to use testify
  commands/user_test.go
Labels: 3: Reviews Complete

#51 Remove go modules workaround
  go.mod
  go.sum
Labels: 3: Reviews Complete

#48 [GH-13112] Add unit tests to "CommandListCmd" to use testify
  commands/command_test.go
Labels: 3: Reviews Complete, QA Review Done

#43 [GH-13124] Add unit tests to "PluginDisableCmd" to use testify
  commands/plugin_test.go
Labels: 3: Reviews Complete, Tests/Not Needed

#44 [GH-13116] Add unit tests to "LdapSyncCmd" to use testify
  commands/ldap_test.go
Labels: 3: Reviews Complete, Tests/Not Needed

#46 [GH-13113] Add unit tests to "CommandDeleteCmd" to use testify
  commands/command_test.go
Labels: 3: Reviews Complete, Tests/Not Needed

#41 [GH-13050] Add unit tests to "SendPasswordResetEmailCmd" to use testify
  commands/user_test.go
Labels: 3: Reviews Complete, QA Review Done

#52 [GH-13110] Add unit tests to "ResetUserMfaCmd" to use testify
  commands/user_test.go
Labels: 3: Reviews Complete, QA Review Done

#53 Bump go version to 1.13 and fix dependency versions in go.mod
  Makefile
  README.md
  go.mod
  go.sum
  magefile.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/github.com/magefile/mage/mg/deps.go
  vendor/github.com/magefile/mage/mg/runtime.go
  vendor/github.com/magefile/mage/sh/cmd.go
  vendor/github.com/magefile/mage/sh/helpers.go
  vendor/github.com/spf13/cobra/.gitignore
  vendor/github.com/spf13/cobra/.travis.yml
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/command_win.go
  vendor/github.com/spf13/cobra/doc/man_docs.go
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/github.com/spf13/cobra/powershell_completions.go
  vendor/github.com/spf13/cobra/powershell_completions.md
  vendor/github.com/spf13/cobra/shell_completions.go
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/github.com/spf13/cobra/zsh_completions.md
  vendor/golang.org/x/net/html/parse.go
  vendor/modules.txt
Labels: 3: Reviews Complete

#59 Add mocks as a PHONY target
  Makefile
Labels: 3: Reviews Complete

#50 Fix naming for CLI plugin list command
  commands/plugin.go
Labels: QA Review Done

#47 [MM-20189] Add unit tests to "updateUserEmailCmd" to use testify
  commands/user_test.go
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#56 [GH-13161] Add unit tests to the "PluginListCmd" mmctl command
  commands/plugin_test.go
Labels: 3: Reviews Complete, QA Review Done

#54 [GH-13123] Add tests for enable plugin command
  commands/plugin_test.go
Labels: QA Review Done, Tests/Not Needed
