Repository mattermost/mmctl, pull requests merged in 2019-12, with the labels that each got.

#45 MM-20192: Add unit tests to "CommandCreateCmd" to use testify
  commands/command_test.go
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#49 GH-13046: Add unit tests to LogsCmd
  commands/logs_test.go
Labels: 2: Dev Review, QA Review Done

#66 Refactor group and permissions command files to use printer
  commands/group.go
  commands/permissions.go
Labels: 2: Dev Review

#55 [MM-19912] Add end to end tests to mmctl
  .circleci/config.yml
  Makefile
  README.md
  commands/mmctl_e2e_test.go
  commands/mmctl_test.go
  commands/mmctl_unit_test.go
  commands/mmctltestlib.go
  commands/plugin_test.go
  commands/user_e2e_test.go
  magefile.go
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#40 [MM-20031] Add unit tests to "userDeactivateCmd" to use testify
  commands/user.go
  commands/user_test.go
Labels: QA Review Done, Tests/Not Needed

#65 Add tests for remove license command
  commands/license_test.go
Labels: 3: Reviews Complete, QA Review Done

#73 fix model import on licence test file for testing
  commands/license_test.go
Labels: 3: Reviews Complete, Tests/Not Needed

#57 Add unit tests to "PluginAddCmd" to use testify
  commands/plugin_test.go
Labels: 3: Reviews Complete, QA Review Done

#62 commands/auth: code polish and refactor error messages
  commands/auth.go
  commands/auth_utils.go
Labels: 3: Reviews Complete

#63 Add two new commands for config: set and reset
  client/client.go
  commands/config.go
  commands/config_test.go
  mocks/client_mock.go
Labels: 3: Reviews Complete

#60 [MM-20287] Add tests for the post create command
  commands/post_test.go
Labels: 3: Reviews Complete, Tests/Not Needed

#68 [MM-20839] Add unit tests to the "TeamCreateCmd"
  commands/team_test.go
Labels: 3: Reviews Complete

#77 Fix logs tests
  commands/logs_test.go
Labels: 3: Reviews Complete, Tests/Not Needed

#75 Remove bad update user email example
  commands/user.go
Labels: 3: Reviews Complete

#69 MM-20824 : Port the "team rename" subcommand from Mattermost CLI to mmctl
  .gitignore
  client/client.go
  commands/team.go
  commands/team_test.go
  commands/teamargs.go
  docs/mmctl.md
  docs/mmctl_config.md
  docs/mmctl_config_reset.md
  docs/mmctl_config_set.md
  docs/mmctl_plugin_list.md
  docs/mmctl_team.md
  docs/mmctl_team_archive.md
  docs/mmctl_team_rename.md
  docs/mmctl_version.md
  mocks/client_mock.go
Labels: 3: Reviews Complete

#83 [GH-13289] Add unit tests to the "TeamGroupEnableCmd" mmctl command
  commands/group_test.go
Labels: 3: Reviews Complete, Tests/Not Needed

#78 GH-13284: Add unit tests to the "RemoveUsersCmd" mmctl command
  commands/team_test.go
Labels: 3: Reviews Complete, Tests/Not Needed
