Repository mattermost/mmctl, pull requests merged in 2020-02, with the labels that each got.

#120 Add ldflags to package target
  Makefile
Labels: 2: Dev Review, CherryPick/Approved

#34 [MM-19066] Added `user list` command
  client/client.go
  commands/user.go
  commands/user_test.go
  docs/mmctl_user.rst
  docs/mmctl_user_list.rst
  mocks/client_mock.go
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#116 Fixes MM-21383 : Add unit tests to the "ChannelRenameCmd" mmctl command
  commands/channel_test.go
Labels: 3: Reviews Complete

#122 [MM-22167] Add custom User-Agent to mmctl's requests
  commands/init.go
Labels: 3: Reviews Complete, QA Review Done

#119 [MM-20290] Add unit tests to the "ShowRoleCmd" mmctl command
  commands/permissions_test.go
Labels: 3: Reviews Complete

#124 Add config edit command
  commands/config.go
  docs/mmctl_config.rst
  docs/mmctl_config_edit.rst
Labels: 3: Reviews Complete, AutoMerge
