Repository mattermost/mmctl, pull requests merged in 2020-05, with the labels that each got.

#158 Migrates the make_private command to use the update channel privacy endpoint
  client/client.go
  commands/channel.go
  mocks/client_mock.go
Labels: 4: Reviews Complete

#161 Checks that socket file has the right permissions and ownership
  commands/init.go
  commands/init_test.go
Labels: 4: Reviews Complete, AutoMerge

#159 [MM-25067] commands/config: use patch method instead of update for set command
  client/client.go
  commands/config.go
  commands/config_test.go
  mocks/client_mock.go
Labels: 4: Reviews Complete

#162 Disable syscall usage for windows build
  commands/init.go
  commands/init_test.go
  commands/utils_unix.go
  commands/utils_unix_test.go
  commands/utils_windows.go
Labels: 4: Reviews Complete

#163 Bump mmctl version to 5.26
  commands/version.go
Labels: 2: Dev Review, 3: QA Review

#165 MM-23725 add team restore
  client/client.go
  commands/team.go
  commands/team_test.go
  docs/mmctl_team.rst
  docs/mmctl_team_restore.rst
  mocks/client_mock.go
Labels: 4: Reviews Complete
