Repository mattermost/mmctl, pull requests merged in 2020-11, with the labels that each got.

#256 [MM-29808] Add e2e test for botDisableCmdF
  commands/bot_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#241 [MM-29340] Added e2e tests to the "channelUsersRemoveCmdF"
  commands/channel_users_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#260 [MM-29802] Add end-2-end tests to generate token for user
  commands/token_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#255 [MM-29807] Add e2e test for botEnableCmdF
  commands/bot_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#273 Bump mmctl version to 5.29
  commands/version.go
Labels: 2: Dev Review

#261 [MM-29732] Added e2e tests to the "configSetCmdF" command
  commands/config_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#239 Add team flag to get user list of a given team
  client/client.go
  commands/user.go
  commands/user_e2e_test.go
  commands/user_test.go
  docs/mmctl_user_list.rst
  mocks/client_mock.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#278 [MM-30264] Increase test timeout
  Makefile
Labels: 4: Reviews Complete

#269 [MM-29806] Add end-2-end tests to bot list command
  commands/bot_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#267 MM-29734 Add end to end tests to the configResetCmdF mmctl command #15982
  commands/config_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#279 [MM-30264] Increase CircleCI no output timeout
  .circleci/config.yml
Labels: 4: Reviews Complete

#265 [MM-29970] Add e2e test for pluginInstallURLCmdF
  commands/plugin_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#280 [MM-30093] enable enterprise tests for e2e tests
  Makefile
  commands/mmctl_test.go
Labels: 4: Reviews Complete

#250 MM-29563 added e2e tests to "modifyCommandCmdF"
  commands/command_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#268 [MM-29809] Add end-2-end tests to bot assign command
  commands/bot_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#277 MM-29969: add e2e test to pluginAddCmdF command
  commands/plugin_e2e_test.go
Labels: 4: Reviews Complete
