Repository mattermost/mmctl, pull requests merged in 2020-01, with the labels that each got.

#81 Add unit tests to the "TeamGroupListCmd" mmctl command
  commands/group_test.go
Labels: 3: Reviews Complete, Tests/Not Needed

#91 [GH13465] Add unit tests to the "ListTeamsCmd" mmctl command
  commands/team_test.go
Labels: 3: Reviews Complete, Tests/Not Needed

#67 [GH-13278] Port the "user activate" subcommand from Mattermost CLI to mmctl
  client/client.go
  commands/user.go
  commands/user_test.go
  mocks/client_mock.go
Labels: 3: Reviews Complete

#80 Add unit tests to the "AddUsersCmd" mmctl command
  commands/team_test.go
Labels: 3: Reviews Complete, Tests/Not Needed

#79 Add unit tests to the "DeleteTeamsCmd" mmctl command
  commands/team_test.go
Labels: 3: Reviews Complete, Tests/Not Needed

#89 Fixes #13399 : Add unit tests to the "TeamGroupStatusCmd" mmctl command
  commands/group_test.go
  docs/mmctl_user_email.md
Labels: 3: Reviews Complete, QA Review Done

#100 Ldflags
  Makefile
Labels: 3: Reviews Complete, Tests/Not Needed

#98 Bump minimum Go version required
  README.md
Labels: 3: Reviews Complete

#101 Added license header to all the .go files
  .circleci/config.yml
  Makefile
  client/client.go
  commands/auth.go
  commands/auth_utils.go
  commands/channel.go
  commands/channel_test.go
  commands/channelargs.go
  commands/command.go
  commands/command_test.go
  commands/completion.go
  commands/config.go
  commands/config_test.go
  commands/docs.go
  commands/group.go
  commands/group_test.go
  commands/init.go
  commands/ldap.go
  commands/ldap_test.go
  commands/license.go
  commands/license_test.go
  commands/logs.go
  commands/logs_test.go
  commands/mmctl_e2e_test.go
  commands/mmctl_test.go
  commands/mmctl_unit_test.go
  commands/mmctltestlib.go
  commands/permissions.go
  commands/permissions_test.go
  commands/plugin.go
  commands/plugin_test.go
  commands/post.go
  commands/post_test.go
  commands/root.go
  commands/team.go
  commands/team_test.go
  commands/teamargs.go
  commands/user.go
  commands/user_e2e_test.go
  commands/user_test.go
  commands/userargs.go
  commands/version.go
  commands/websockets.go
  magefile.go
  mmctl.go
  mocks/client_mock.go
  mocks/copyright.txt
  printer/printer.go
Labels: 3: Reviews Complete, Tests/Not Needed

#72 MM-20838 Add unit tests to the "ConfigShowCmd" mmctl command
  commands/config_test.go
Labels: 3: Reviews Complete, QA Review Done

#76 [MM-20836] Add unit tests to the "TeamGroupDisableCmd" mmctl command
  commands/group_test.go
Labels: 3: Reviews Complete, QA Review Done

#84 [GH-13402] Add unit tests to the "ListLdapGroupsCmd" mmctl command
  commands/group_test.go
Labels: 3: Reviews Complete, Tests/Not Needed

#85 GH-13404: Add 3 test cases for removePermissionsCmdF
  commands/permissions_test.go
Labels: 3: Reviews Complete, Tests/Not Needed

#86 Fixes #13401 : Add unit tests to the "ChannelGroupStatusCmd" mmctl command
  commands/group.go
  commands/group_test.go
  docs/mmctl_user.md
  docs/mmctl_user_activate.md
Labels: 3: Reviews Complete, QA Review Done

#92 [GH13121] Add unit tests to "PluginDeleteCmd" to use testify
  commands/plugin.go
  commands/plugin_test.go
Labels: 3: Reviews Complete, QA Review Done

#88 MM-20752 - MMCTL config get option doesn't allow to pass plugin ids
  commands/config.go
  commands/config_test.go
  commands/plugin_test.go
Labels: 3: Reviews Complete

#93 GH-13533 : Change channel rename command to be uniform with team rename
  commands/channel.go
  docs/mmctl_channel.md
  docs/mmctl_channel_rename.md
Labels: 2: Dev Review, QA Review Done

#99 [GH-13400] Add unit test for TestChannelGroupListCmd
  commands/group_test.go
Labels: 3: Reviews Complete, Tests/Not Needed

#87 GH-13291: Add unit tests to ChannelGroupEnableCmdF mmctl command
  commands/group_test.go
Labels: 3: Reviews Complete

#104 [MM-21705] Make sure docs are updated
  .circleci/config.yml
Labels: 3: Reviews Complete

#106 Update docs
  docs/mmctl_team_users.md
  docs/mmctl_team_users_remove.md
Labels: 3: Reviews Complete

#82 GH-13290 Add unit tests to the ChannelGroupDisableCmd mmctl command
  commands/group_test.go
Labels: 3: Reviews Complete, Tests/Not Needed

#90 [MM-21381] Add unit tests to the "SearchTeamCmd" mmctl command
  commands/team.go
  commands/team_test.go
Labels: 3: Reviews Complete, QA Review Done

#108 Some changes suggested to improve consistency
  commands/command.go
  commands/command_test.go
  docs/mmctl_command_archive.md
  docs/mmctl_command_list.md
Labels: 3: Reviews Complete, Tests/Not Needed

#94 GH-13460: Add unit tests for AddChannelUsersCmd mmctl command.
  commands/channel.go
  commands/channel_test.go
Labels: QA Review Done

#109 Added tFatal and equalLenAsserts checkers
  Makefile
Labels: 3: Reviews Complete, Tests/Not Needed

#97 [GH-13459] Add unit tests to the "ArchiveChannelsCmd" mmctl command
  commands/channel.go
  commands/channel_test.go
Labels: QA Review Done

#107 Start using golanci linter
  .circleci/config.yml
  .golangci.yml
  Makefile
  commands/auth.go
  commands/auth_utils.go
  commands/channel.go
  commands/channel_test.go
  commands/channelargs.go
  commands/command.go
  commands/command_test.go
  commands/completion.go
  commands/config.go
  commands/config_test.go
  commands/docs.go
  commands/group.go
  commands/group_test.go
  commands/init.go
  commands/ldap.go
  commands/ldap_test.go
  commands/license.go
  commands/license_test.go
  commands/logs.go
  commands/logs_test.go
  commands/mmctl_test.go
  commands/mmctltestlib.go
  commands/permissions.go
  commands/plugin.go
  commands/plugin_test.go
  commands/post.go
  commands/post_test.go
  commands/root.go
  commands/team.go
  commands/team_test.go
  commands/team_users.go
  commands/team_users_test.go
  commands/teamargs.go
  commands/user.go
  commands/user_e2e_test.go
  commands/user_test.go
  commands/userargs.go
  printer/printer.go
Labels: 3: Reviews Complete, Tests/Not Needed

#105 [GH-13282] Port the "channel modify" subcommand from Mattermost CLI to mmctl
  client/client.go
  commands/channel.go
  commands/channel_test.go
  docs/mmctl_channel.md
  docs/mmctl_channel_modify.md
  mocks/client_mock.go
Labels: 3: Reviews Complete, QA Review Done

#113 Fix lint errors
  commands/channel.go
  commands/channel_test.go
Labels: Tests/Not Needed

#115 Fixes windows build
  commands/auth.go
Labels: 3: Reviews Complete

#110 [GH-13457] Add unit tests to the "RestoreChannelsCmd" mmctl command
  commands/channel_test.go
Labels: 3: Reviews Complete

#114 Adding a checksum value and commenting out windows build since it is …
  .circleci/config.yml
  Makefile
Labels: 3: Reviews Complete

#118 Fixes the error message shown when the strict mode is enabled
  commands/init.go
Labels: 3: Reviews Complete, CherryPick/Approved
