Repository mattermost/mmctl, pull requests merged in 2020-03, with the labels that each got.

#127 commands/channel: use formatted string on errors
  commands/channel.go
  commands/channel_test.go
Labels: 3: Reviews Complete

#129 Issue 128: fix panic in 'command list' without args
  commands/command.go
Labels: 3: Reviews Complete

#125 [MM-22168] commands/user: do not call API if there is a ".." in query
  commands/channel_test.go
  commands/channelargs.go
  commands/command_test.go
  commands/commandargs.go
  commands/teamargs.go
  commands/user_test.go
  commands/userargs.go
Labels: 3: Reviews Complete, CherryPick/Approved

#132 [MM-23036] Remove the name flag from the team rename command
  commands/team.go
  commands/team_test.go
  docs/mmctl_team_rename.rst
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#131 Add coverage report
  .circleci/config.yml
  .gitignore
  Makefile
  README.md
Labels: 3: Reviews Complete

#135 MM-23031 support team:trigger syntax
  commands/command_test.go
  commands/commandargs.go
Labels: QA Review Done

#126 Printer: add tests
  printer/printer.go
  printer/printer_test.go
Labels: 3: Reviews Complete

#140 Bump mmctl version to 5.24.0
  commands/version.go
Labels: 3: Reviews Complete

#134 [MM-22794] commands/bot: add bot creation command
  client/client.go
  commands/bot.go
  commands/bot_test.go
  docs/mmctl.rst
  docs/mmctl_bot.rst
  docs/mmctl_bot_create.rst
  mocks/client_mock.go
Labels: 3: Reviews Complete

#133 [MM-22795] commands/user: add token generation and retrieving tokens
  client/client.go
  commands/token.go
  commands/token_test.go
  docs/mmctl.rst
  docs/mmctl_token.rst
  docs/mmctl_token_generate.rst
  docs/mmctl_token_list.rst
  docs/mmctl_token_revoke.rst
  mmctl.md5.txt
  mocks/client_mock.go
Labels: QA Review Done

#142 IS-299: Checkout server over HTTPS on CircleCI
  .circleci/config.yml
Labels: 3: Reviews Complete, AutoMerge

#145 Fix linter error from latest gosimple
  commands/post.go
Labels: AutoMerge

#144 Add Apache2 license file
  LICENSE.txt
Labels: AutoMerge, QA Review Done
