Repository mattermost/mmctl, pull requests merged in 2020-08, with the labels that each got.

#185 MM-27285 fix panic in bot list
  commands/bot.go
  commands/bot_test.go
Labels: QA Review Done

#179 [MM-25648] commands/user: add user convert command
  client/client.go
  commands/user.go
  commands/user_test.go
  docs/mmctl_user.rst
  docs/mmctl_user_convert.rst
  mocks/client_mock.go
Labels: 4: Reviews Complete

#189 [MM-27650] Add disable local precheck and disable commands that were not implemented for phase 2
  commands/bot.go
  commands/channel.go
  commands/init.go
  commands/team.go
Labels: 4: Reviews Complete

#191 [MM-13991] Add channel users subcommand and deprecate channel add and remove
  commands/channel.go
  commands/channel_test.go
  commands/channel_users.go
  commands/channel_users_test.go
  docs/mmctl_channel.rst
  docs/mmctl_channel_users.rst
  docs/mmctl_channel_users_add.rst
  docs/mmctl_channel_users_remove.rst
Labels: 4: Reviews Complete

#194 [MM-28098] Add user change-password command
  client/client.go
  commands/auth.go
  commands/user.go
  commands/user_test.go
  docs/mmctl_user.rst
  docs/mmctl_user_change-password.rst
  docs/mmctl_user_convert.rst
  docs/mmctl_user_create.rst
  docs/mmctl_user_delete.rst
  docs/mmctl_user_deleteall.rst
  go.mod
  go.sum
  mocks/client_mock.go
  vendor/github.com/mattermost/mattermost-server/v5/model/client4.go
  vendor/github.com/mattermost/mattermost-server/v5/model/config.go
  vendor/github.com/mattermost/mattermost-server/v5/model/license.go
  vendor/github.com/mattermost/mattermost-server/v5/model/migration.go
  vendor/github.com/mattermost/mattermost-server/v5/model/permission.go
  vendor/github.com/mattermost/mattermost-server/v5/model/role.go
  vendor/github.com/mattermost/mattermost-server/v5/model/system.go
  vendor/modules.txt
Labels: 4: Reviews Complete, AutoMerge
