Repository mattermost/mmctl, pull requests merged in 2020-10, with the labels that each got.

#210 [MM-29193] Add system status command
  client/client.go
  commands/system.go
  commands/system_test.go
  docs/mmctl_system.rst
  docs/mmctl_system_status.rst
  mocks/client_mock.go
Labels: 4: Reviews Complete

#217 added PHONY for all make targets
  Makefile
Labels: 4: Reviews Complete, Hacktoberfest

#225 Makes every test reset the printer state
  commands/mmctl_test.go
Labels: 4: Reviews Complete

#208 Add end to end tests to the renameTeamCmdF mmctl command
  commands/team_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#226 [MM-29230] Add e2e tests to teamUsersAddCmdF
  commands/team_users_e2e_test.go
Labels: 4: Reviews Complete, AutoMerge, Hacktoberfest, hacktoberfest-accepted

#229 [MM-29265] Add end to end tests to the "unarchiveChannelsCmdF" mmctl command
  commands/channel_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#216 [MM-29053] prevent using format for logs
  commands/logs.go
  commands/logs_test.go
  docs/mmctl_logs.rst
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#238 [MM-29637] Remove local guards for migrated commands
  commands/channel.go
  commands/team.go
Labels: 4: Reviews Complete, CherryPick/Candidate

#223 Add e2e tests for archiveTeamsCmdF
  commands/team_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#224 Add e2e tests for createChannelCmd
  commands/channel_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#242 Fix linter for golangci new versions
  commands/group_test.go
  commands/init.go
Labels: 4: Reviews Complete

#207 add end to end tests for function deleteUsersCmdF
  commands/user_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#246 Update golangci-lint to v1.31.0
  .circleci/config.yml
Labels: 4: Reviews Complete

#204 MM-28675: add e2e tests to updateUserEmailCmdF command
  commands/user.go
  commands/user_e2e_test.go
Labels: 4: Reviews Complete

#213 [MM-28671] Add end-2-ends tests for user create command
  commands/user_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#240 [MM-29172] Add E2E tests for teamUsersRemoveCmdF
  commands/team_users_e2e_test.go
Labels: 4: Reviews Complete, AutoMerge, Hacktoberfest, hacktoberfest-accepted

#215 [MM-29167] Add e2e tests for searchTeamCmdF
  commands/team_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#235 [MM-29336] Add e2e tests to channelUsersAddCmdF
  commands/channel_users_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#233 Add e2e tests for searchChannelCmdF
  commands/channel_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#211 add e2e test case user deleteall
  commands/user_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#227 [MM-29154] Added multiple assertions in e2e test for `verifyUserEmailWithoutTokenCmdF` method
  commands/user_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#228 [GH-15677] Add e2e tests to the 'restoreTeamsCmdF' mmctl command
  commands/team_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#222 [MM-29164] Add e2e tests to createTeamCmdF
  commands/team_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#212 add e2e test case user reset mfa
  commands/user_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#205 [MM-28672] Add e2e testing for user invite
  commands/user_e2e_test.go
Labels: 4: Reviews Complete

#219 Add end to end tests to the 'userConvertCmdF' mmctl command
  commands/user_e2e_test.go
Labels: 3: QA Review, Hacktoberfest, hacktoberfest-accepted

#206 add end to end test for function listUsersCmdF
  commands/user_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#236 [MM 29334] adding e2e test for moveChannelCmdF.
  commands/channel_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, QA Review Done, hacktoberfest-accepted

#221 [GH-15734] add e2e test for 'listChannelsCmdF' (#15734)
  commands/channel_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#231 [MM-29166] Add e2e tests to listTeamsCmdF
  commands/team_e2e_test.go
Labels: 2: Dev Review, Hacktoberfest, QA Review Done, hacktoberfest-accepted

#262 Fix user error messages in tests
  commands/user_e2e_test.go
Labels: 4: Reviews Complete

#232 [MM-29332] Add e2e tests to renameChannelCmdF
  commands/channel_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, QA Review Done, hacktoberfest-accepted

#234 MM-29170: Add e2e tests to modify teams command
  commands/team.go
  commands/team_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, QA Review Done, hacktoberfest-accepted

#249 [MM-29562]: add e2e tests to archiveCommandCmdF
  commands/command_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, QA Review Done, hacktoberfest-accepted

#253 [MM-29566] Add e2e test for pluginMarketplaceInstallCmdF
  commands/plugin_marketplace_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, QA Review Done, hacktoberfest-accepted

#254 [MM-29335] end to end tests for delete channels
  commands/channel_e2e_test.go
Labels: 2: Dev Review, Hacktoberfest, QA Review Done, hacktoberfest-accepted

#259 Add .idea folder to gitignore
  .gitignore
Labels: Hacktoberfest, hacktoberfest-accepted

#243 Fixes ifelsechain warning pointing the nolint directive to the right linter
  commands/bot.go
Labels: 4: Reviews Complete

#258 [MM-29568] Add E2E tests for configGetCmdF
  commands/config_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#218 Add end to end tests to the 'deleteTeamsCmdF' mmctl command
  commands/team_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#252 [MM-29561] Added e2e tests to the "listCommandCmdF
  commands/command_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, QA Review Done, hacktoberfest-accepted

#257 [MM-29523] New flag for user creation command
  commands/user.go
  commands/user_e2e_test.go
  docs/mmctl_user_create.rst
  go.mod
  go.sum
  vendor/github.com/mattermost/mattermost-server/v5/api4/cloud.go
  vendor/github.com/mattermost/mattermost-server/v5/api4/user.go
  vendor/github.com/mattermost/mattermost-server/v5/app/app_iface.go
  vendor/github.com/mattermost/mattermost-server/v5/app/cloud.go
  vendor/github.com/mattermost/mattermost-server/v5/app/email.go
  vendor/github.com/mattermost/mattermost-server/v5/app/opentracing/opentracing_layer.go
  vendor/github.com/mattermost/mattermost-server/v5/app/plugin.go
  vendor/github.com/mattermost/mattermost-server/v5/einterfaces/cloud.go
  vendor/github.com/mattermost/mattermost-server/v5/model/client4.go
  vendor/github.com/mattermost/mattermost-server/v5/model/cloud.go
  vendor/github.com/mattermost/mattermost-server/v5/model/marketplace_plugin.go
  vendor/github.com/mattermost/mattermost-server/v5/model/user.go
  vendor/github.com/mattermost/mattermost-server/v5/web/context.go
  vendor/github.com/mattermost/mattermost-server/v5/web/params.go
  vendor/modules.txt
Labels: QA Review Done

#32 GH-12960 Adds roles subcommand
  commands/roles.go
  commands/roles_test.go
Labels: Lifecycle/2:inactive

#264 Add docs and small modifications to the commands
  commands/roles.go
  commands/roles_test.go
  docs/mmctl.rst
  docs/mmctl_roles.rst
  docs/mmctl_roles_member.rst
  docs/mmctl_roles_system_admin.rst
Labels: 2: Dev Review

#272 Bump mmctl version to 5.30
  commands/version.go
Labels: 2: Dev Review
