Repository mattermost/mmctl, pull requests merged in 2020-04, with the labels that each got.

#143 [MM-22343] commands/post: do not set online when creating a post
  client/client.go
  commands/post.go
  commands/post_test.go
  mocks/client_mock.go
Labels: 3: Reviews Complete, QA Review Done

#141 Adding new bot actions
  client/client.go
  commands/bot.go
  commands/bot_test.go
  docs/mmctl_bot.rst
  docs/mmctl_bot_assign.rst
  docs/mmctl_bot_disable.rst
  docs/mmctl_bot_enable.rst
  docs/mmctl_bot_list.rst
  docs/mmctl_bot_update.rst
  mocks/client_mock.go
Labels: 3: Reviews Complete, QA Review Done

#152 Fix bot list loop logic and related tests
  commands/bot.go
  commands/bot_test.go
  docs/mmctl_bot_disable.rst
Labels: QA Review Done

#147 [GH-13461] add unit tests to the RemoveChannelUsersCmd mmctl command
  commands/channel_test.go
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#139 [MM-23482] Make team list iterate until it gets all server teams
  commands/team.go
  commands/team_test.go
  go.sum
Labels: 3: Reviews Complete, AutoMerge

#146 [GH-13463] add unit tests to the ChannelCreateCmd mmctl command
  commands/channel_test.go
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#157 MM-24294: Check the type before assigning a value to a slice
  commands/config.go
  commands/config_test.go
  docs/mmctl_config_set.rst
Labels: QA Review Done
