Repository mattermost/mmctl, pull requests merged in 2020-06, with the labels that each got.

#148 add unit tests to the UploadLicenseCmd mmctl command
  commands/license_test.go
Labels: 3: QA Review

#168 MM-24448: trim trailing slash from url
  commands/auth.go
  commands/auth_e2e_test.go
  commands/mmctltestlib.go
Labels: 4: Reviews Complete

#167 [MM-21501] commands/channel: add unarchive alias to restore channel cmd
  commands/channel.go
  commands/channel_test.go
  docs/mmctl_channel.rst
  docs/mmctl_channel_unarchive.rst
Labels: 4: Reviews Complete

#149 [MM-23720] commands/channel: add move channel command
  client/client.go
  commands/channel.go
  commands/channel_test.go
  commands/group_test.go
  commands/license_test.go
  docs/mmctl_channel.rst
  docs/mmctl_channel_move.rst
  go.mod
  go.sum
  mocks/client_mock.go
  vendor/github.com/mattermost/mattermost-server/v5/model/auditconv.go
  vendor/github.com/mattermost/mattermost-server/v5/model/client4.go
  vendor/github.com/mattermost/mattermost-server/v5/model/cluster_message.go
  vendor/github.com/mattermost/mattermost-server/v5/model/config.go
  vendor/github.com/mattermost/mattermost-server/v5/model/group.go
  vendor/github.com/mattermost/mattermost-server/v5/model/job.go
  vendor/github.com/mattermost/mattermost-server/v5/model/license.go
  vendor/github.com/mattermost/mattermost-server/v5/model/marketplace_plugin.go
  vendor/github.com/mattermost/mattermost-server/v5/model/push_notification.go
  vendor/github.com/mattermost/mattermost-server/v5/model/session.go
  vendor/github.com/mattermost/mattermost-server/v5/model/system.go
  vendor/github.com/mattermost/mattermost-server/v5/model/typing_request.go
  vendor/github.com/mattermost/mattermost-server/v5/model/user_get.go
  vendor/github.com/mattermost/mattermost-server/v5/model/user_search.go
  vendor/github.com/mattermost/mattermost-server/v5/model/version.go
  vendor/modules.txt
Labels: 4: Reviews Complete

#151 [MM-23726] commands/user: add verify user command
  client/client.go
  commands/user.go
  commands/user_test.go
  docs/mmctl_user.rst
  docs/mmctl_user_verify.rst
  go.mod
  go.sum
  mocks/client_mock.go
  vendor/github.com/mattermost/mattermost-server/v5/model/client4.go
  vendor/github.com/mattermost/mattermost-server/v5/model/command_args.go
  vendor/github.com/mattermost/mattermost-server/v5/model/config.go
  vendor/github.com/mattermost/mattermost-server/v5/model/group.go
  vendor/github.com/mattermost/mattermost-server/v5/model/team.go
  vendor/modules.txt
Labels: 4: Reviews Complete

#170 [MM-25646] Adds deleteall user command
  client/client.go
  commands/init.go
  commands/team.go
  commands/team_test.go
  commands/user.go
  commands/user_test.go
  docs/mmctl_user.rst
  docs/mmctl_user_deleteall.rst
  go.mod
  go.sum
  mocks/client_mock.go
  vendor/github.com/mattermost/mattermost-server/v5/model/client4.go
  vendor/modules.txt
Labels: QA Review Done
