Repository mattermost/mmctl, pull requests merged in 2020-12, with the labels that each got.

#33 Adds webhook subcommand
  client/client.go
  commands/webhook.go
  commands/webhook_test.go
  docs/mmctl.rst
  docs/mmctl_webhook.rst
  docs/mmctl_webhook_create-incoming.rst
  docs/mmctl_webhook_create-outgoing.rst
  docs/mmctl_webhook_delete.rst
  docs/mmctl_webhook_list.rst
  docs/mmctl_webhook_modify-incoming.rst
  docs/mmctl_webhook_modify-outgoing.rst
  docs/mmctl_webhook_show.rst
  mocks/client_mock.go
Labels: 4: Reviews Complete

#276 MM-29810 added e2e tests to "logsCmdF"
  commands/logs_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#287 Fix docs config-path flag for webhooks
  docs/mmctl_webhook.rst
  docs/mmctl_webhook_create-incoming.rst
  docs/mmctl_webhook_create-outgoing.rst
  docs/mmctl_webhook_delete.rst
  docs/mmctl_webhook_list.rst
  docs/mmctl_webhook_modify-incoming.rst
  docs/mmctl_webhook_modify-outgoing.rst
  docs/mmctl_webhook_show.rst
Labels: 2: Dev Review

#281 [MM-30298] commands/permissions_role: add e2e test
  commands/permissions_role_e2e_test.go
Labels: 4: Reviews Complete

#288 Lock CI from cloud/release-5.30
  .circleci/config.yml
Labels: AutoMerge

#293 Lock CI from cloud/release-5.31
  .circleci/config.yml
  .gitlab-ci.yml
Labels: AutoMerge
