Repository mattermost/mmctl, pull requests merged in 2021-06, with the labels that each got.

#321 feat(commands): added displaying user roles on update
  commands/roles.go
  commands/roles_test.go
Labels: 4: Reviews Complete, QA Review Done

#309 DOC: Moved Compile and Developer sections below "usage"
  README.md
Labels: 4: Reviews Complete

#360 Remove local mode only check from commands after system bot was merged
  commands/channel.go
Labels: 4: Reviews Complete

#318 [15945]Add end to end tests to the "pluginMarketplaceListCmdF" mmctl command
  commands/plugin_marketplace_e2e_test.go
Labels: 4: Reviews Complete, AutoMerge
