Repository mattermost/mmctl, pull requests merged in 2021-08, with the labels that each got.

#292 [MM-25650] Add sampledata command
  commands/sampledata.go
  commands/sampledata_test.go
  commands/sampledata_util.go
  commands/utils.go
  docs/mmctl.rst
  docs/mmctl_sampledata.rst
  go.mod
  go.sum
  vendor/github.com/corpix/uarand/.gitignore
  vendor/github.com/corpix/uarand/.travis.yml
  vendor/github.com/corpix/uarand/LICENSE
  vendor/github.com/corpix/uarand/Makefile
  vendor/github.com/corpix/uarand/README.md
  vendor/github.com/corpix/uarand/go.mod
  vendor/github.com/corpix/uarand/go.sum
  vendor/github.com/corpix/uarand/shell.nix
  vendor/github.com/corpix/uarand/uarand.go
  vendor/github.com/corpix/uarand/useragents.go
  vendor/github.com/icrowley/fake/.gitignore
  vendor/github.com/icrowley/fake/.go-makefile.json
  vendor/github.com/icrowley/fake/.travis.yml
  vendor/github.com/icrowley/fake/LICENSE
  vendor/github.com/icrowley/fake/Makefile
  vendor/github.com/icrowley/fake/README.md
  vendor/github.com/icrowley/fake/addresses.go
  vendor/github.com/icrowley/fake/credit_cards.go
  vendor/github.com/icrowley/fake/currencies.go
  vendor/github.com/icrowley/fake/data.go
  vendor/github.com/icrowley/fake/dates.go
  vendor/github.com/icrowley/fake/fake.go
  vendor/github.com/icrowley/fake/general.go
  vendor/github.com/icrowley/fake/geo.go
  vendor/github.com/icrowley/fake/glide.lock
  vendor/github.com/icrowley/fake/glide.yaml
  vendor/github.com/icrowley/fake/internet.go
  vendor/github.com/icrowley/fake/jobs.go
  vendor/github.com/icrowley/fake/lorem_ipsum.go
  vendor/github.com/icrowley/fake/names.go
  vendor/github.com/icrowley/fake/personal.go
  vendor/github.com/icrowley/fake/products.go
  vendor/modules.txt
Labels: 4: Reviews Complete

#368 [MM-36562] Implement `extract` command
  commands/extract.go
  commands/extract_e2e_test.go
  docs/mmctl.rst
  docs/mmctl_extract.rst
  docs/mmctl_extract_job.rst
  docs/mmctl_extract_job_list.rst
  docs/mmctl_extract_job_show.rst
  docs/mmctl_extract_run.rst
  go.mod
  go.sum
  vendor/code.sajari.com/docconv/.travis.yml
  vendor/code.sajari.com/docconv/README.md
  vendor/code.sajari.com/docconv/go.mod
  vendor/code.sajari.com/docconv/go.sum
  vendor/code.sajari.com/docconv/local.go
  vendor/code.sajari.com/docconv/pages.go
  vendor/code.sajari.com/docconv/rtf.go
  vendor/code.sajari.com/docconv/tidy.go
  vendor/github.com/mattermost/mattermost-server/v6/api4/post.go
  vendor/github.com/mattermost/mattermost-server/v6/api4/system.go
  vendor/github.com/mattermost/mattermost-server/v6/app/app_iface.go
  vendor/github.com/mattermost/mattermost-server/v6/app/enterprise.go
  vendor/github.com/mattermost/mattermost-server/v6/app/job.go
  vendor/github.com/mattermost/mattermost-server/v6/app/notification.go
  vendor/github.com/mattermost/mattermost-server/v6/app/opentracing/opentracing_layer.go
  vendor/github.com/mattermost/mattermost-server/v6/app/permissions_migrations.go
  vendor/github.com/mattermost/mattermost-server/v6/app/plugin_requests.go
  vendor/github.com/mattermost/mattermost-server/v6/app/post.go
  vendor/github.com/mattermost/mattermost-server/v6/app/post_metadata.go
  vendor/github.com/mattermost/mattermost-server/v6/app/server.go
  vendor/github.com/mattermost/mattermost-server/v6/app/user.go
  vendor/github.com/mattermost/mattermost-server/v6/jobs/interfaces/extract_content_interface.go
  vendor/github.com/mattermost/mattermost-server/v6/jobs/jobs_watcher.go
  vendor/github.com/mattermost/mattermost-server/v6/jobs/server.go
  vendor/github.com/mattermost/mattermost-server/v6/jobs/workers.go
  vendor/github.com/mattermost/mattermost-server/v6/model/client4.go
  vendor/github.com/mattermost/mattermost-server/v6/model/feature_flags.go
  vendor/github.com/mattermost/mattermost-server/v6/model/job.go
  vendor/github.com/mattermost/mattermost-server/v6/plugin/api.go
  vendor/github.com/mattermost/mattermost-server/v6/plugin/context.go
  vendor/github.com/mattermost/mattermost-server/v6/services/docextractor/documents.go
  vendor/github.com/mattermost/mattermost-server/v6/store/sqlstore/status_store.go
  vendor/github.com/mattermost/mattermost-server/v6/store/sqlstore/store.go
  vendor/github.com/mattermost/mattermost-server/v6/store/sqlstore/system_store.go
  vendor/github.com/mattermost/mattermost-server/v6/store/sqlstore/thread_store.go
  vendor/github.com/mattermost/mattermost-server/v6/store/sqlstore/upgrade.go
  vendor/github.com/mattermost/mattermost-server/v6/store/store.go
  vendor/github.com/mattermost/mattermost-server/v6/store/storetest/system_store.go
  vendor/modules.txt
Labels: 4: Reviews Complete

#375 [MM-37687] Add pagination to channel list command
  commands/channel.go
  commands/channel_test.go
Labels: 4: Reviews Complete

#374 Update idmigrate docs
  commands/ldap.go
  docs/mmctl_ldap_idmigrate.rst
Labels: 4: Reviews Complete

#372 Check the terminal if it's interactive and abstarct the confirmation to a utility function
  commands/channel.go
  commands/channel_test.go
  commands/config.go
  commands/integrity.go
  commands/saml.go
  commands/saml_test.go
  commands/team.go
  commands/team_test.go
  commands/user.go
  commands/user_e2e_test.go
  commands/user_test.go
  commands/utils.go
Labels: 4: Reviews Complete

#379 bugfix: Do not check local mode socket owner if current user is root
  commands/utils_unix.go
Labels: 4: Reviews Complete, AutoMerge

#364 convert underscore in flags and commands to use hyphens
  commands/channel.go
  commands/channel_e2e_test.go
  commands/channel_test.go
  commands/roles.go
  commands/team.go
  commands/team_e2e_test.go
  commands/team_test.go
  commands/user.go
  commands/user_e2e_test.go
  commands/user_test.go
  docs/mmctl_channel.rst
  docs/mmctl_channel_create.rst
  docs/mmctl_channel_make-private.rst
  docs/mmctl_channel_rename.rst
  docs/mmctl_roles.rst
  docs/mmctl_roles_system-admin.rst
  docs/mmctl_team_rename.rst
  docs/mmctl_user.rst
  docs/mmctl_user_convert.rst
  docs/mmctl_user_create.rst
  docs/mmctl_user_migrate-auth.rst
  docs/mmctl_user_migrate_auth.rst
  docs/mmctl_user_reset-password.rst
Labels: 4: Reviews Complete

#370 encourage users to not copy their secrets on shell history
  commands/auth.go
  commands/auth_utils.go
  commands/auth_utils_test.go
  docs/mmctl_auth_login.rst
  docs/mmctl_auth_renew.rst
Labels: 4: Reviews Complete

#380 add yes/no prompt
  commands/utils.go
  go.mod
  go.sum
  vendor/github.com/isacikgoz/fuzzy/.gitignore
  vendor/github.com/isacikgoz/fuzzy/CONTRIBUTING.md
  vendor/github.com/isacikgoz/fuzzy/LICENSE
  vendor/github.com/isacikgoz/fuzzy/README.md
  vendor/github.com/isacikgoz/fuzzy/fuzzy.go
  vendor/github.com/isacikgoz/fuzzy/go.mod
  vendor/github.com/isacikgoz/fuzzy/go.sum
  vendor/github.com/isacikgoz/prompt/README.md
  vendor/github.com/isacikgoz/prompt/async_list.go
  vendor/github.com/isacikgoz/prompt/go.mod
  vendor/github.com/isacikgoz/prompt/go.sum
  vendor/github.com/isacikgoz/prompt/list.go
  vendor/github.com/isacikgoz/prompt/prompt.go
  vendor/github.com/isacikgoz/prompt/renderer.go
  vendor/github.com/isacikgoz/prompt/selection.go
  vendor/github.com/isacikgoz/prompt/sync_list.go
  vendor/github.com/isacikgoz/prompt/term/bufferedreader.go
  vendor/github.com/isacikgoz/prompt/term/bufferedwriter.go
  vendor/github.com/isacikgoz/prompt/term/consants_bsd.go
  vendor/github.com/isacikgoz/prompt/term/constants_common.go
  vendor/github.com/isacikgoz/prompt/term/constants_linux.go
  vendor/github.com/isacikgoz/prompt/term/keycodes.go
  vendor/github.com/isacikgoz/prompt/term/runereader.go
  vendor/github.com/isacikgoz/prompt/term/terminal.go
  vendor/modules.txt
Labels: 4: Reviews Complete

#381 [Build] Support go 1.17
  commands/main_test.go
  commands/mmctl_e2e_test.go
  commands/mmctl_unit_test.go
  commands/utils_unix.go
  magefile.go
Labels: 2: Dev Review
