Repository mattermost/mmctl, pull requests merged in 2021-03, with the labels that each got.

#326 Lock CI from /release-5.33
  .circleci/config.yml
  .gitlab-ci.yml
  Makefile
Labels: AutoMerge

#330 Bump version to 5.33
  commands/version.go
Labels: 4: Reviews Complete

#334 commands/plugin_marketplace_e2e_test: fix plugin version
  commands/plugin_marketplace_e2e_test.go
Labels: 4: Reviews Complete

#335 Adds export e2e test ids
  commands/export_e2e_test.go
Labels: 4: Reviews Complete, QA Review Done

#327 [MM-32943] commands/user: add promote/demote user commands
  client/client.go
  commands/user.go
  commands/user_e2e_test.go
  commands/user_test.go
  docs/mmctl_user.rst
  docs/mmctl_user_create.rst
  docs/mmctl_user_demote.rst
  docs/mmctl_user_promote.rst
  mocks/client_mock.go
Labels: 4: Reviews Complete

#329 [MM-21225] commands/bot: enable creating access token after a bot creation
  commands/bot.go
  commands/bot_e2e_test.go
  commands/bot_test.go
  docs/mmctl_bot_create.rst
Labels: 4: Reviews Complete

#338 commands/group: add e2e tests batch 2
  commands/group_e2e_test.go
Labels: 4: Reviews Complete
