Repository mattermost/mmctl, pull requests merged in 2021-01, with the labels that each got.

#297 MM-31882 - Add CodeQL check
  .github/workflows/codeql-analysis.yml
Labels: 4: Reviews Complete

#289 Add new subcommand name to the command user for changing username of a user account #248
  commands/user.go
  commands/user_e2e_test.go
  docs/mmctl_user.rst
  docs/mmctl_user_username.rst
Labels: QA Review Done

#302 Fix docs
  docs/mmctl_user_username.rst
Labels: 4: Reviews Complete

#304 [MM-30267] add e2e tests to coverage
  .circleci/config.yml
  .gitlab-ci.yml
  Makefile
Labels: 4: Reviews Complete

#300 [GH-16076] Add end to end tests to the "pluginDeleteCmdF" mmctl command
  commands/plugin_e2e_test.go
Labels: 4: Reviews Complete, QA Review Done
