Repository mattermost/mmctl, pull requests merged in 2021-04, with the labels that each got.

#339 commands/permissions and commands/permissions_role: add some e2e tests (batch 3)
  commands/permissions_e2e_test.go
  commands/permissions_role_e2e_test.go
Labels: 2: Dev Review, QA Review Done

#340 commands/license and commands/ststem: add some e2e tests (batch 4)
  commands/license_e2e_test.go
  commands/system_e2e_test.go
Labels: 4: Reviews Complete

#337 commands/group, commands/ldap: add e2e tests batch 1
  Makefile
  commands/group_e2e_test.go
  commands/ldap_e2e_test.go
Labels: 4: Reviews Complete

#342 [MM-32044] Reset SAML auth data
  client/client.go
  commands/saml.go
  commands/saml_test.go
  docs/mmctl.rst
  docs/mmctl_saml.rst
  docs/mmctl_saml_auth-data-reset.rst
  go.mod
  go.sum
  mocks/client_mock.go
  vendor/github.com/mattermost/mattermost-server/v5/api4/saml.go
  vendor/github.com/mattermost/mattermost-server/v5/app/admin.go
  vendor/github.com/mattermost/mattermost-server/v5/app/app.go
  vendor/github.com/mattermost/mattermost-server/v5/app/app_iface.go
  vendor/github.com/mattermost/mattermost-server/v5/app/config.go
  vendor/github.com/mattermost/mattermost-server/v5/app/email.go
  vendor/github.com/mattermost/mattermost-server/v5/app/opentracing/opentracing_layer.go
  vendor/github.com/mattermost/mattermost-server/v5/app/saml.go
  vendor/github.com/mattermost/mattermost-server/v5/app/security_update_check.go
  vendor/github.com/mattermost/mattermost-server/v5/app/server.go
  vendor/github.com/mattermost/mattermost-server/v5/einterfaces/saml.go
  vendor/github.com/mattermost/mattermost-server/v5/model/client4.go
  vendor/github.com/mattermost/mattermost-server/v5/shared/mail/inbucket.go
  vendor/github.com/mattermost/mattermost-server/v5/shared/mail/mail.go
  vendor/github.com/mattermost/mattermost-server/v5/store/sqlstore/user_store.go
  vendor/modules.txt
Labels: 2: Dev Review, 3: QA Review, AutoMerge

#348 Add documentation changes to reflect those in the product docs
  commands/channel.go
  commands/user.go
  docs/mmctl_channel_make_private.rst
  docs/mmctl_channel_modify.rst
  docs/mmctl_user_convert.rst
  docs/mmctl_user_email.rst
  docs/mmctl_user_resetmfa.rst
  docs/mmctl_user_verify.rst
Labels: 4: Reviews Complete

#294 MM 28114 refactor entity commands
  commands/channel_users.go
  commands/channelargs.go
  commands/channelargs_test.go
  commands/errors.go
  commands/teamargs.go
  commands/teamargs_test.go
  commands/user.go
  commands/user_e2e_test.go
  commands/user_test.go
  commands/userargs.go
  commands/userargs_test.go
  go.mod
Labels: 4: Reviews Complete
