Repository mattermost/mmctl, pull requests merged in 2022-10, with the labels that each got.

#560 [GH-21223] Add error handling for pluginInstallUvRLCmdF
  commands/plugin.go
  commands/plugin_e2e_test.go
  commands/plugin_test.go
Labels: Hacktoberfest, hacktoberfest-accepted

#566 ref: return multi error
  commands/channel.go
  commands/channel_e2e_test.go
  commands/channel_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#579 [MM-47398] add http proxy support
  commands/init.go
  commands/init_test.go
Labels: 4: Reviews Complete

#561 refact: adding error handling for assignUsersCmdF
  commands/permission_role_test.go
  commands/permissions_role.go
  commands/permissions_role_e2e_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#592 [MM-47825] refactor rolesSystemAdminCmdF function to return an error #21477
  commands/roles.go
  commands/roles_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#593 Refactored verifyUserEmailWithoutTokenCmdF function to return an erro…
  commands/user.go
  commands/user_e2e_test.go
  commands/user_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#596 [MM-47810] Return error from rolesMemberCmdF
  commands/roles.go
  commands/roles_test.go
Labels: Hacktoberfest, hacktoberfest-accepted

#598 Refactored resetUserMfaCmdF to return multierror
  commands/user.go
  commands/user_e2e_test.go
  commands/user_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#587 MM-47825 demoteUserToGuestCmdF function to return an error in case of…
  commands/user.go
  commands/user_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#586 [MM-47823] SendPasswordResetEmailCmdF command error handle refactoring
  commands/user.go
  commands/user_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#589 [MM-47814] - Refactor deleteTeamsCmdF function error handling
  commands/team.go
  commands/team_e2e_test.go
  commands/team_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted
