Repository mattermost/mmctl, pull requests merged in 2022-11, with the labels that each got.

#600 [MM-47351] | Add error handling for integrityCmdF function
  commands/integrity.go
  commands/integrity_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#595 [MM-47818] userInviteCmdF function to return an error in case of a failure
  commands/user.go
  commands/user_e2e_test.go
  commands/user_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#588 MM-47817: Review changeUsersActiveStatus function to return an error in case of a failure
  commands/user.go
  commands/user_e2e_test.go
  commands/user_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#604 Update README.md
  README.md
Labels: 4: Reviews Complete

#603 [MM-47812] Refactor addUserToTeam function to return an error
  commands/team_users.go
  commands/team_users_e2e_test.go
  commands/team_users_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#564 MM-47355: Added multierr for postListCmdF (#21222)
  commands/post.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#581 Refact: restoreTeamsCmdF() - Error handling
  commands/team.go
  commands/team_e2e_test.go
  commands/team_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#577 Issue 21220: improve error handling for botEnableCmdF function
  commands/bot.go
  commands/bot_e2e_test.go
  commands/bot_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#576 Issue 21219: improve error handling for botDisableCmdF
  commands/bot.go
  commands/bot_e2e_test.go
  commands/bot_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#570 ref: return multi-error from moveChannelCmdF
  commands/channel.go
  commands/channel_e2e_test.go
  commands/channel_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#573 MM-47344: added multerror result for listChannelsCmdF (#21215)
  commands/channel.go
  commands/channel_e2e_test.go
  commands/channel_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#602 Refactor | Creating error at return and update tests
  commands/channel.go
  commands/plugin_e2e_test.go
  commands/plugin_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#599 refact: removeAllUsersFromChannel to return an error
  commands/channel_users.go
  commands/channel_users_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#612 commands/plugin_e2_test: fix an error assertion issue
  commands/plugin_e2e_test.go
Labels: 4: Reviews Complete

#462 Add SECURITY.md
  SECURITY.md
Labels: 4: Reviews Complete

#400 Update intro and add logo
  README.md
Labels: 2: Dev Review

#569 [GH-21210] refactor(commands): add error handling to listCommandCmdF
  commands/command.go
  commands/command_e2e_test.go
  commands/command_test.go
  commands/enterprise.go
Labels: Hacktoberfest, hacktoberfest-accepted

#460 [MM-15983] Added e2e testing for configShowCmdf
  commands/config_e2e_test.go
Labels: 2: Dev Review

#568 #21213 - Add error handling for archiveChannelsCmdF
  commands/channel.go
  commands/channel_e2e_test.go
  commands/channel_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted
